name: "Daily runner"
on:
  schedule:
    - cron: "00 12 * * *"
  push:
    branches:
      - main

jobs:
  croner:
    runs-on: ubuntu-latest
    steps:
        - name: "Harden Runner"
          uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
          with:
            egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

        - name: "Checkout"
          uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
          with:
            fetch-depth: 0
            submodules: true

        - name: "Set up python"
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: "Run script"
          run: |
            pip install -r requirements.txt
            GH_TOKEN="${{ secrets.GITHUB_TOKEN }}" python create_csv.py

        - name: "Get current date"
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

        - name: "commit the csv back to the repo"
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add taxonomy_stats.csv
            git commit -m "Added the stats for ${{ steps.date.outputs.date }}"
            git push
